services:
  graphql-gateway:
    build: ./graphql-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - user-service
      - organization-service
    environment:
      AUTH_SERVICE_URL: "auth-service:50051"
      USER_SERVICE_URL: "user-service:50052"
      ORG_SERVICE_URL: "organization-service:50053"

  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "auth-service"
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "50052:50052"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "user-service"
    depends_on:
      - postgres

  organization-service:
    build: ./organization-service
    ports:
      - "50053:50053"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "organization-service"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
  #   ports:
  #     - "9200:9200"

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.10.1
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.10.1
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
    depends_on:
      - zookeeper


  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start-dev
    ports:
      - "8080:8080"
volumes:
  pgdata:
    driver: local
