version: "3.8"

networks:
  pixerp-network:
    driver: bridge

services:
  # --------------------------------------------------
  # Postgres Container
  # --------------------------------------------------
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: pixerp
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - pixerp-network

  # --------------------------------------------------
  # Keycloak
  # --------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start-dev
    ports:
      - "8080:8080"

  # --------------------------------------------------
  # GraphQL Gateway
  # --------------------------------------------------
  graphql-gateway:
    build: ./graphql-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - user-service
      - organization-service
    environment:
      AUTH_SERVICE_URL: "auth-service:50051"
      USER_SERVICE_URL: "user-service:50052"
      ORG_SERVICE_URL: "organization-service:50053"

  # --------------------------------------------------
  # Auth Service
  # --------------------------------------------------
  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    depends_on:
      - keycloak
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "auth-service"    

  # --------------------------------------------------
  # User Service
  # --------------------------------------------------
  user-service:
    build: ./user-service
    ports:
      - "50052:50052"
    depends_on:
      - auth-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "user-service"

  # --------------------------------------------------
  # Organization Service
  # --------------------------------------------------
  organization-service:
    build: ./organization-service
    ports:
      - "50053:50053"
    depends_on:
      - auth-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "organization-service"

  # --------------------------------------------------
  # CRM Services
  # --------------------------------------------------
  activity-task-service:
    build: ./modules/crm/activity-task-service
    ports:
      - "50057:50057"
    depends_on:
      - organization-service
      - graphql-gateway
      - user-service
      - contact-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "activity-task-service"

  contact-service:
    build: ./modules/crm/contacts-service
    ports:
      - "50056:50056"
    depends_on:
      - graphql-gateway
      - user-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "contact-service"

  leads-service:
    build: ./modules/crm/leads-service
    ports:
      - "50054:50054"
    depends_on:
      - graphql-gateway
      - user-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "leads-service"

  opportunity-service:
    build: ./modules/crm/opportunity-service
    ports:
      - "50055:50055"
    depends_on:
      - graphql-gateway
      - user-service
      - contact-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "opportunity-service"

  # --------------------------------------------------
  # Finance Service
  # --------------------------------------------------
  finance-service:
    build: ./modules/finance-service
    ports:
      - "50002:50002"
    depends_on:
      - graphql-gateway
      - user-service
      - organization-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "finance-service"

  # --------------------------------------------------
  # Inventory Service
  # --------------------------------------------------
  inventory-service:
    build: ./modules/inventory-service
    ports:
      - "50003:50003"
    depends_on:
      - graphql-gateway
      - user-service
      - organization-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "inventory-service"

  # --------------------------------------------------
  # VMS Service
  # --------------------------------------------------
  vms-service:
    build: ./modules/vms-service
    ports:
      - "50004:50004"
    depends_on:
      - graphql-gateway
      - user-service
      - organization-service
    environment:
      DB_HOST: "localhost"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "vms-service"

volumes:
  pgdata:
    driver: local
