version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: start-dev
    ports:
      - "8080:8080"

  graphql-gateway:
    build: ./graphql-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - user-service
      - organization-service
    environment:
      AUTH_SERVICE_URL: "auth-service:50051"
      USER_SERVICE_URL: "user-service:50052"
      ORG_SERVICE_URL: "organization-service:50053"

  auth-service:
    build: ./auth-service
    ports:
      - "50051:50051"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "auth-service"
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "50052:50052"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "user-service"
    depends_on:
      - postgres

  organization-service:
    build: ./organization-service
    ports:
      - "50053:50053"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "organization-service"
    depends_on:
      - postgres

  activity-task-service:
    build: ./modules/crm/activity-task-service
    ports:
      - "50057:50057"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pixerp"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service
      - contact-service

  contact-service:
    build: ./modules/crm/contact-service
    ports:
      - "50056:50056"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pixerp"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service

  leads-service:
    build: ./modules/crm/leads-service
    ports:
      - "50054:50054"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pixerp"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service

  opportunity-service:
    build: ./modules/crm/opportunity-service
    ports:
      - "50055:50055"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pixerp"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service
      - contact-service

  finance-service:
    build: ./modules/finance-service
    ports:
      - "50002:50002"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "vms-service"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service
      - organization-service

  inventory-service:
    build: ./modules/inventory-service
    ports:
      - "50003:50003"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "inventory-service"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service
      - organization-service

  vms-service:
    build: ./modules/vms-service
    ports:
      - "50004:50004"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "vms-service"
    depends_on:
      - postgres
      - graphql-gateway
      - user-service
      - organization-service

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
