// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0--rc2
// source: asset_disposal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DisposalService_DecommissionAsset_FullMethodName = "/disposal.DisposalService/DecommissionAsset"
)

// DisposalServiceClient is the client API for DisposalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DisposalServiceClient interface {
	DecommissionAsset(ctx context.Context, in *DecommissionAssetRequest, opts ...grpc.CallOption) (*DecommissionResponse, error)
}

type disposalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDisposalServiceClient(cc grpc.ClientConnInterface) DisposalServiceClient {
	return &disposalServiceClient{cc}
}

func (c *disposalServiceClient) DecommissionAsset(ctx context.Context, in *DecommissionAssetRequest, opts ...grpc.CallOption) (*DecommissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecommissionResponse)
	err := c.cc.Invoke(ctx, DisposalService_DecommissionAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisposalServiceServer is the server API for DisposalService service.
// All implementations must embed UnimplementedDisposalServiceServer
// for forward compatibility.
type DisposalServiceServer interface {
	DecommissionAsset(context.Context, *DecommissionAssetRequest) (*DecommissionResponse, error)
	mustEmbedUnimplementedDisposalServiceServer()
}

// UnimplementedDisposalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDisposalServiceServer struct{}

func (UnimplementedDisposalServiceServer) DecommissionAsset(context.Context, *DecommissionAssetRequest) (*DecommissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecommissionAsset not implemented")
}
func (UnimplementedDisposalServiceServer) mustEmbedUnimplementedDisposalServiceServer() {}
func (UnimplementedDisposalServiceServer) testEmbeddedByValue()                         {}

// UnsafeDisposalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DisposalServiceServer will
// result in compilation errors.
type UnsafeDisposalServiceServer interface {
	mustEmbedUnimplementedDisposalServiceServer()
}

func RegisterDisposalServiceServer(s grpc.ServiceRegistrar, srv DisposalServiceServer) {
	// If the following call pancis, it indicates UnimplementedDisposalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DisposalService_ServiceDesc, srv)
}

func _DisposalService_DecommissionAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecommissionAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisposalServiceServer).DecommissionAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DisposalService_DecommissionAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisposalServiceServer).DecommissionAsset(ctx, req.(*DecommissionAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DisposalService_ServiceDesc is the grpc.ServiceDesc for DisposalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DisposalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "disposal.DisposalService",
	HandlerType: (*DisposalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecommissionAsset",
			Handler:    _DisposalService_DecommissionAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asset_disposal.proto",
}
