// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: internal/api/protobufs/gstr3b.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GSTR3BRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gstin        string `protobuf:"bytes,1,opt,name=gstin,proto3" json:"gstin,omitempty"`
	ReturnPeriod string `protobuf:"bytes,2,opt,name=return_period,json=returnPeriod,proto3" json:"return_period,omitempty"`
	TaxableValue string `protobuf:"bytes,3,opt,name=taxable_value,json=taxableValue,proto3" json:"taxable_value,omitempty"`
	TaxLiability string `protobuf:"bytes,4,opt,name=tax_liability,json=taxLiability,proto3" json:"tax_liability,omitempty"`
	ItcClaimed   string `protobuf:"bytes,5,opt,name=itc_claimed,json=itcClaimed,proto3" json:"itc_claimed,omitempty"`
}

func (x *GSTR3BRequest) Reset() {
	*x = GSTR3BRequest{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BRequest) ProtoMessage() {}

func (x *GSTR3BRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BRequest.ProtoReflect.Descriptor instead.
func (*GSTR3BRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{0}
}

func (x *GSTR3BRequest) GetGstin() string {
	if x != nil {
		return x.Gstin
	}
	return ""
}

func (x *GSTR3BRequest) GetReturnPeriod() string {
	if x != nil {
		return x.ReturnPeriod
	}
	return ""
}

func (x *GSTR3BRequest) GetTaxableValue() string {
	if x != nil {
		return x.TaxableValue
	}
	return ""
}

func (x *GSTR3BRequest) GetTaxLiability() string {
	if x != nil {
		return x.TaxLiability
	}
	return ""
}

func (x *GSTR3BRequest) GetItcClaimed() string {
	if x != nil {
		return x.ItcClaimed
	}
	return ""
}

type GSTR3BResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefId  string `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GSTR3BResponse) Reset() {
	*x = GSTR3BResponse{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BResponse) ProtoMessage() {}

func (x *GSTR3BResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BResponse.ProtoReflect.Descriptor instead.
func (*GSTR3BResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{1}
}

func (x *GSTR3BResponse) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

func (x *GSTR3BResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GSTR3BSubmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gstin        string `protobuf:"bytes,1,opt,name=gstin,proto3" json:"gstin,omitempty"`
	ReturnPeriod string `protobuf:"bytes,2,opt,name=return_period,json=returnPeriod,proto3" json:"return_period,omitempty"`
}

func (x *GSTR3BSubmitRequest) Reset() {
	*x = GSTR3BSubmitRequest{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BSubmitRequest) ProtoMessage() {}

func (x *GSTR3BSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BSubmitRequest.ProtoReflect.Descriptor instead.
func (*GSTR3BSubmitRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{2}
}

func (x *GSTR3BSubmitRequest) GetGstin() string {
	if x != nil {
		return x.Gstin
	}
	return ""
}

func (x *GSTR3BSubmitRequest) GetReturnPeriod() string {
	if x != nil {
		return x.ReturnPeriod
	}
	return ""
}

type GSTR3BSubmitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arn    string `protobuf:"bytes,1,opt,name=arn,proto3" json:"arn,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GSTR3BSubmitResponse) Reset() {
	*x = GSTR3BSubmitResponse{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BSubmitResponse) ProtoMessage() {}

func (x *GSTR3BSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BSubmitResponse.ProtoReflect.Descriptor instead.
func (*GSTR3BSubmitResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{3}
}

func (x *GSTR3BSubmitResponse) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

func (x *GSTR3BSubmitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GSTR3BFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gstin        string `protobuf:"bytes,1,opt,name=gstin,proto3" json:"gstin,omitempty"`
	ReturnPeriod string `protobuf:"bytes,2,opt,name=return_period,json=returnPeriod,proto3" json:"return_period,omitempty"`
	Arn          string `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
}

func (x *GSTR3BFileRequest) Reset() {
	*x = GSTR3BFileRequest{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BFileRequest) ProtoMessage() {}

func (x *GSTR3BFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BFileRequest.ProtoReflect.Descriptor instead.
func (*GSTR3BFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{4}
}

func (x *GSTR3BFileRequest) GetGstin() string {
	if x != nil {
		return x.Gstin
	}
	return ""
}

func (x *GSTR3BFileRequest) GetReturnPeriod() string {
	if x != nil {
		return x.ReturnPeriod
	}
	return ""
}

func (x *GSTR3BFileRequest) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type GSTR3BFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilingStatus string `protobuf:"bytes,1,opt,name=filing_status,json=filingStatus,proto3" json:"filing_status,omitempty"`
	Message      string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GSTR3BFileResponse) Reset() {
	*x = GSTR3BFileResponse{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BFileResponse) ProtoMessage() {}

func (x *GSTR3BFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BFileResponse.ProtoReflect.Descriptor instead.
func (*GSTR3BFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{5}
}

func (x *GSTR3BFileResponse) GetFilingStatus() string {
	if x != nil {
		return x.FilingStatus
	}
	return ""
}

func (x *GSTR3BFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GSTR3BStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gstin        string `protobuf:"bytes,1,opt,name=gstin,proto3" json:"gstin,omitempty"`
	ReturnPeriod string `protobuf:"bytes,2,opt,name=return_period,json=returnPeriod,proto3" json:"return_period,omitempty"`
	Arn          string `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
}

func (x *GSTR3BStatusRequest) Reset() {
	*x = GSTR3BStatusRequest{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BStatusRequest) ProtoMessage() {}

func (x *GSTR3BStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BStatusRequest.ProtoReflect.Descriptor instead.
func (*GSTR3BStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{6}
}

func (x *GSTR3BStatusRequest) GetGstin() string {
	if x != nil {
		return x.Gstin
	}
	return ""
}

func (x *GSTR3BStatusRequest) GetReturnPeriod() string {
	if x != nil {
		return x.ReturnPeriod
	}
	return ""
}

func (x *GSTR3BStatusRequest) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type GSTR3BStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GSTR3BStatusResponse) Reset() {
	*x = GSTR3BStatusResponse{}
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GSTR3BStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GSTR3BStatusResponse) ProtoMessage() {}

func (x *GSTR3BStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_protobufs_gstr3b_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GSTR3BStatusResponse.ProtoReflect.Descriptor instead.
func (*GSTR3BStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_protobufs_gstr3b_proto_rawDescGZIP(), []int{7}
}

func (x *GSTR3BStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GSTR3BStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_api_protobufs_gstr3b_proto protoreflect.FileDescriptor

var file_internal_api_protobufs_gstr3b_proto_rawDesc = []byte{
	0x0a, 0x23, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x67, 0x73, 0x74, 0x72, 0x33, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x0d, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x78, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x61, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x78, 0x5f, 0x6c,
	0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x74, 0x61, 0x78, 0x4c, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x74, 0x63, 0x5f, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x74, 0x63, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x65, 0x64, 0x22, 0x3f, 0x0a,
	0x0e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x15, 0x0a, 0x06, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x66, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x50,
	0x0a, 0x13, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x22, 0x40, 0x0a, 0x14, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x60, 0x0a, 0x11, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x61, 0x72, 0x6e, 0x22, 0x53, 0x0a, 0x12, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69,
	0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x13, 0x47, 0x53, 0x54,
	0x52, 0x33, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x67, 0x73, 0x74, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61,
	0x72, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x6e, 0x22, 0x48, 0x0a,
	0x14, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xf2, 0x01, 0x0a, 0x0d, 0x47, 0x53, 0x54, 0x52,
	0x33, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x53, 0x61, 0x76,
	0x65, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x12, 0x0e, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x12, 0x14, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33,
	0x42, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x53, 0x54,
	0x52, 0x33, 0x42, 0x12, 0x12, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x53, 0x54, 0x52, 0x33, 0x42, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x67, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_api_protobufs_gstr3b_proto_rawDescOnce sync.Once
	file_internal_api_protobufs_gstr3b_proto_rawDescData = file_internal_api_protobufs_gstr3b_proto_rawDesc
)

func file_internal_api_protobufs_gstr3b_proto_rawDescGZIP() []byte {
	file_internal_api_protobufs_gstr3b_proto_rawDescOnce.Do(func() {
		file_internal_api_protobufs_gstr3b_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_api_protobufs_gstr3b_proto_rawDescData)
	})
	return file_internal_api_protobufs_gstr3b_proto_rawDescData
}

var file_internal_api_protobufs_gstr3b_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_api_protobufs_gstr3b_proto_goTypes = []any{
	(*GSTR3BRequest)(nil),        // 0: GSTR3BRequest
	(*GSTR3BResponse)(nil),       // 1: GSTR3BResponse
	(*GSTR3BSubmitRequest)(nil),  // 2: GSTR3BSubmitRequest
	(*GSTR3BSubmitResponse)(nil), // 3: GSTR3BSubmitResponse
	(*GSTR3BFileRequest)(nil),    // 4: GSTR3BFileRequest
	(*GSTR3BFileResponse)(nil),   // 5: GSTR3BFileResponse
	(*GSTR3BStatusRequest)(nil),  // 6: GSTR3BStatusRequest
	(*GSTR3BStatusResponse)(nil), // 7: GSTR3BStatusResponse
}
var file_internal_api_protobufs_gstr3b_proto_depIdxs = []int32{
	0, // 0: GSTR3BService.SaveGSTR3B:input_type -> GSTR3BRequest
	2, // 1: GSTR3BService.SubmitGSTR3B:input_type -> GSTR3BSubmitRequest
	4, // 2: GSTR3BService.FileGSTR3B:input_type -> GSTR3BFileRequest
	6, // 3: GSTR3BService.GetGSTR3BStatus:input_type -> GSTR3BStatusRequest
	1, // 4: GSTR3BService.SaveGSTR3B:output_type -> GSTR3BResponse
	3, // 5: GSTR3BService.SubmitGSTR3B:output_type -> GSTR3BSubmitResponse
	5, // 6: GSTR3BService.FileGSTR3B:output_type -> GSTR3BFileResponse
	7, // 7: GSTR3BService.GetGSTR3BStatus:output_type -> GSTR3BStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_protobufs_gstr3b_proto_init() }
func file_internal_api_protobufs_gstr3b_proto_init() {
	if File_internal_api_protobufs_gstr3b_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_api_protobufs_gstr3b_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_protobufs_gstr3b_proto_goTypes,
		DependencyIndexes: file_internal_api_protobufs_gstr3b_proto_depIdxs,
		MessageInfos:      file_internal_api_protobufs_gstr3b_proto_msgTypes,
	}.Build()
	File_internal_api_protobufs_gstr3b_proto = out.File
	file_internal_api_protobufs_gstr3b_proto_rawDesc = nil
	file_internal_api_protobufs_gstr3b_proto_goTypes = nil
	file_internal_api_protobufs_gstr3b_proto_depIdxs = nil
}
