grpc:
  port: ":50054"

websocket:
  addr: ":8000"

database:
  url: "postgres://postgres:root@host.docker.internal:5432/leads-service?sslmode=disable"

keycloak:
  url: "http://host.docker.internal:8080"
